[build]
  publish = "public/"
  command = "echo 'No build needed for edge functions'"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

# No build command needed for edge functions
[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/api/email"
  function = "email"

[[edge_functions]]
  path = "/api/debug-env"
  function = "debug-env"

[[edge_functions]]
  path = "/api/test-azure-auth"
  function = "test-azure-auth"

[[edge_functions]]
  path = "/api/current-time"
  function = "current-time"